// Code generated by qtc from "facets_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vlselect/logsql/facets_response.qtpl:1
package logsql

//line app/vlselect/logsql/facets_response.qtpl:1
import (
	"slices"
	"sort"
)

//line app/vlselect/logsql/facets_response.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vlselect/logsql/facets_response.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vlselect/logsql/facets_response.qtpl:8
func StreamFacetsResponse(qw422016 *qt422016.Writer, m map[string][]facetEntry) {
//line app/vlselect/logsql/facets_response.qtpl:8
	qw422016.N().S(`{`)
//line app/vlselect/logsql/facets_response.qtpl:11
	sortedKeys := make([]string, 0, len(m))
	for k := range m {
		sortedKeys = append(sortedKeys, k)
	}
	slices.Sort(sortedKeys)

//line app/vlselect/logsql/facets_response.qtpl:16
	qw422016.N().S(`"facets":[`)
//line app/vlselect/logsql/facets_response.qtpl:18
	if len(sortedKeys) > 0 {
//line app/vlselect/logsql/facets_response.qtpl:19
		streamfacetsLine(qw422016, m, sortedKeys[0])
//line app/vlselect/logsql/facets_response.qtpl:20
		for _, k := range sortedKeys[1:] {
//line app/vlselect/logsql/facets_response.qtpl:20
			qw422016.N().S(`,`)
//line app/vlselect/logsql/facets_response.qtpl:21
			streamfacetsLine(qw422016, m, k)
//line app/vlselect/logsql/facets_response.qtpl:22
		}
//line app/vlselect/logsql/facets_response.qtpl:23
	}
//line app/vlselect/logsql/facets_response.qtpl:23
	qw422016.N().S(`]}`)
//line app/vlselect/logsql/facets_response.qtpl:26
}

//line app/vlselect/logsql/facets_response.qtpl:26
func WriteFacetsResponse(qq422016 qtio422016.Writer, m map[string][]facetEntry) {
//line app/vlselect/logsql/facets_response.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/logsql/facets_response.qtpl:26
	StreamFacetsResponse(qw422016, m)
//line app/vlselect/logsql/facets_response.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/logsql/facets_response.qtpl:26
}

//line app/vlselect/logsql/facets_response.qtpl:26
func FacetsResponse(m map[string][]facetEntry) string {
//line app/vlselect/logsql/facets_response.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/logsql/facets_response.qtpl:26
	WriteFacetsResponse(qb422016, m)
//line app/vlselect/logsql/facets_response.qtpl:26
	qs422016 := string(qb422016.B)
//line app/vlselect/logsql/facets_response.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/logsql/facets_response.qtpl:26
	return qs422016
//line app/vlselect/logsql/facets_response.qtpl:26
}

//line app/vlselect/logsql/facets_response.qtpl:28
func streamfacetsLine(qw422016 *qt422016.Writer, m map[string][]facetEntry, k string) {
//line app/vlselect/logsql/facets_response.qtpl:28
	qw422016.N().S(`{"field_name":`)
//line app/vlselect/logsql/facets_response.qtpl:30
	qw422016.N().Q(k)
//line app/vlselect/logsql/facets_response.qtpl:30
	qw422016.N().S(`,"values":[`)
//line app/vlselect/logsql/facets_response.qtpl:33
	fes := m[k]
	sort.Slice(fes, func(i, j int) bool {
		a, b := &fes[i], &fes[j]
		return a.hits > b.hits || a.value < b.value
	})

//line app/vlselect/logsql/facets_response.qtpl:39
	if len(fes) > 0 {
//line app/vlselect/logsql/facets_response.qtpl:40
		streamfacetLine(qw422016, fes[0])
//line app/vlselect/logsql/facets_response.qtpl:41
		for _, fe := range fes[1:] {
//line app/vlselect/logsql/facets_response.qtpl:41
			qw422016.N().S(`,`)
//line app/vlselect/logsql/facets_response.qtpl:42
			streamfacetLine(qw422016, fe)
//line app/vlselect/logsql/facets_response.qtpl:43
		}
//line app/vlselect/logsql/facets_response.qtpl:44
	}
//line app/vlselect/logsql/facets_response.qtpl:44
	qw422016.N().S(`]}`)
//line app/vlselect/logsql/facets_response.qtpl:47
}

//line app/vlselect/logsql/facets_response.qtpl:47
func writefacetsLine(qq422016 qtio422016.Writer, m map[string][]facetEntry, k string) {
//line app/vlselect/logsql/facets_response.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/logsql/facets_response.qtpl:47
	streamfacetsLine(qw422016, m, k)
//line app/vlselect/logsql/facets_response.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/logsql/facets_response.qtpl:47
}

//line app/vlselect/logsql/facets_response.qtpl:47
func facetsLine(m map[string][]facetEntry, k string) string {
//line app/vlselect/logsql/facets_response.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/logsql/facets_response.qtpl:47
	writefacetsLine(qb422016, m, k)
//line app/vlselect/logsql/facets_response.qtpl:47
	qs422016 := string(qb422016.B)
//line app/vlselect/logsql/facets_response.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/logsql/facets_response.qtpl:47
	return qs422016
//line app/vlselect/logsql/facets_response.qtpl:47
}

//line app/vlselect/logsql/facets_response.qtpl:49
func streamfacetLine(qw422016 *qt422016.Writer, fe facetEntry) {
//line app/vlselect/logsql/facets_response.qtpl:49
	qw422016.N().S(`{"field_value":`)
//line app/vlselect/logsql/facets_response.qtpl:51
	qw422016.N().Q(fe.value)
//line app/vlselect/logsql/facets_response.qtpl:51
	qw422016.N().S(`,"hits":`)
//line app/vlselect/logsql/facets_response.qtpl:52
	qw422016.N().S(fe.hits)
//line app/vlselect/logsql/facets_response.qtpl:52
	qw422016.N().S(`}`)
//line app/vlselect/logsql/facets_response.qtpl:54
}

//line app/vlselect/logsql/facets_response.qtpl:54
func writefacetLine(qq422016 qtio422016.Writer, fe facetEntry) {
//line app/vlselect/logsql/facets_response.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/logsql/facets_response.qtpl:54
	streamfacetLine(qw422016, fe)
//line app/vlselect/logsql/facets_response.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/logsql/facets_response.qtpl:54
}

//line app/vlselect/logsql/facets_response.qtpl:54
func facetLine(fe facetEntry) string {
//line app/vlselect/logsql/facets_response.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/logsql/facets_response.qtpl:54
	writefacetLine(qb422016, fe)
//line app/vlselect/logsql/facets_response.qtpl:54
	qs422016 := string(qb422016.B)
//line app/vlselect/logsql/facets_response.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/logsql/facets_response.qtpl:54
	return qs422016
//line app/vlselect/logsql/facets_response.qtpl:54
}
